// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

type Trend struct {
	TrendsID                 []byte `json:"trends_id"`
	TrendsName               string `json:"trends_name"`
	TrendsLocation           string `json:"trends_location"`
	TrendsRank               int32  `json:"trends_rank"`
	TrendsEndtimestamp       int32  `json:"trends_endtimestamp"`
	TrendsIncreasePercentage int32  `json:"trends_increase_percentage"`
}
