// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: saveTrend.sql

package sqlc

import (
	"context"
)

const deleteTrend = `-- name: deleteTrend :exec
DELETE FROM trends
`

func (q *Queries) deleteTrend(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTrend)
	return err
}

const saveTrend = `-- name: saveTrend :exec
INSERT INTO trends (trends_name,trends_location,trends_rank) VALUES (?, ?, ?)
`

type saveTrendParams struct {
	TrendsName     string `json:"trends_name"`
	TrendsLocation string `json:"trends_location"`
	TrendsRank     int32  `json:"trends_rank"`
}

func (q *Queries) saveTrend(ctx context.Context, arg saveTrendParams) error {
	_, err := q.db.ExecContext(ctx, saveTrend, arg.TrendsName, arg.TrendsLocation, arg.TrendsRank)
	return err
}
