// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: saveTrend.sql

package sqlc

import (
	"context"
)

const deleteTrend = `-- name: DeleteTrend :exec
DELETE FROM trends
`

func (q *Queries) DeleteTrend(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTrend)
	return err
}

const saveTrend = `-- name: SaveTrend :exec
INSERT INTO trends (trends_name,trends_location,trends_rank,trends_endtimestamp,trends_increase_percentage) VALUES (?, ?, ?, ?, ?)
`

type SaveTrendParams struct {
	TrendsName               string `json:"trends_name"`
	TrendsLocation           string `json:"trends_location"`
	TrendsRank               int32  `json:"trends_rank"`
	TrendsEndtimestamp       int32  `json:"trends_endtimestamp"`
	TrendsIncreasePercentage int32  `json:"trends_increase_percentage"`
}

func (q *Queries) SaveTrend(ctx context.Context, arg SaveTrendParams) error {
	_, err := q.db.ExecContext(ctx, saveTrend,
		arg.TrendsName,
		arg.TrendsLocation,
		arg.TrendsRank,
		arg.TrendsEndtimestamp,
		arg.TrendsIncreasePercentage,
	)
	return err
}
